# These are supported funding model platforms

github: # Your GitHub username, e.g. [akshaykg]
patreon: # Your Patreon username
open_collective: # Your Open Collective username
ko_fi: # Your Ko-fi username
tidelift: # Your Tidelift package, e.g. npm/package-name
community_bridge: # Your Community Bridge project
liberapay: # Your Liberapay username
issuehunt: # Your IssueHunt username
polar: # Your Polar username
buy_me_a_coffee: # Your Buy Me a Coffee username
custom: # Custom URLs, e.g. ['https://your-link.com']
